{% set name = "pyxem" %}
{% set version = "0.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 60a878fc06f990782d7611c8dca86157ddff11d2d4c9ea0f3a95c10e674dc1f1


build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3.7
    - dask-core >=2021.8.1
    - diffsims >=0.5
    - hyperspy-base >=2.0
    - h5py
    - lmfit >=0.9.12
    - matplotlib-base >=3.6
    - numba
    - numpy
    - numexpr !=2.8.6
    - orix >=0.9
    - pooch
    - psutil
    - pyfai-base <=2023.9.0
    - scikit-image >=0.19.0,!=0.21.0
    - scikit-learn >=1.0
    - shapely
    - scipy
    - tqdm
    - traits
    - transforms3d
    - zarr

test:
  requires:
    - pytest>=5.0
    - pytest-rerunfailures
    - pytest-xdist
  imports:
    - pyxem
    - pyxem.components
    - pyxem.detectors
    - pyxem.data
    - pyxem.generators
    - pyxem.libraries
    - pyxem.signals
    - pyxem.utils
  commands:
    - pytest --pyargs pyxem --reruns 2 -n 2

about:
  home: https://github.com/pyxem/pyxem
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for crystallographic diffraction microscopy
  doc_url: https://pyxem.readthedocs.io

extra:
  recipe-maintainers:
    - CSSFrancis
    - hakonanes
    - dnjohnstone
    - pc494
    - magnunor
