{% set name = "pyxem" %}
{% set version = "0.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a78d4fe1880c2f8033fb6b8245ce5f7a475bb8f6deede6a7c9d4ed57302b5cd4


build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - dask-core >=2021.8.1
    - diffsims >=0.7
    - hyperspy-base >=2.0
    - h5py
    - lmfit >=0.9.12
    - matplotlib-base >=3.7.5
    - numba
    - numpy
    - numexpr !=2.8.6
    - orix >=0.12.1
    - pooch
    - psutil
    - scikit-image >=0.19.0,!=0.21.0
    - scikit-learn >=1.0
    - shapely >2.0
    - scipy
    - tqdm
    - traits
    - transforms3d
    - zarr < 3.0.0

test:
  requires:
    - pytest>=5.0
    - pytest-rerunfailures
    - pytest-xdist
    - python {{ python_min }}
  imports:
    - pyxem
    - pyxem.components
    - pyxem.data
    - pyxem.generators
    - pyxem.libraries
    - pyxem.signals
    - pyxem.utils
  commands:
    - pytest --pyargs pyxem --reruns 2 -n 2

about:
  home: https://github.com/pyxem/pyxem
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for crystallographic diffraction microscopy
  doc_url: https://pyxem.readthedocs.io

extra:
  recipe-maintainers:
    - CSSFrancis
    - hakonanes
    - dnjohnstone
    - pc494
    - magnunor
