{% set name = "pyxem" %}
{% set version = "0.16.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6be051f28530af117de27ff0f62c6843a9eaf96430bff18ba23ab16744b93684


build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - dask-core >=2021.8.1
    - diffsims >=0.5
    - hyperspy-base >=1.7.0,<2.0rc0
    - h5py
    - lmfit >=0.9.12
    - matplotlib-base >=3.3
    - numba
    - numpy
    - numexpr !=2.8.6
    - orix >=0.9
    - pooch
    - psutil
    - pyfai-base
    - scikit-image >=0.19.0,!=0.21.0
    - scikit-learn >=1.0
    - scipy
    - tqdm
    - traits
    - transforms3d

test:
  requires:
    - pytest>=5.0
    - pytest-rerunfailures
    - pytest-xdist
  imports:
    - pyxem
    - pyxem.components
    - pyxem.detectors
    - pyxem.data
    - pyxem.dummy_data
    - pyxem.generators
    - pyxem.libraries
    - pyxem.signals
    - pyxem.utils
  commands:
    - pytest --pyargs pyxem --reruns 2 -n 2

about:
  home: https://github.com/pyxem/pyxem
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for crystallographic diffraction microscopy
  doc_url: https://pyxem.readthedocs.io

extra:
  recipe-maintainers:
    - CSSFrancis
    - hakonanes
    - dnjohnstone
    - pc494
    - magnunor
